### ISSUE TITLE
Identification for pomodoro or a break

### ISSUE THREAD

**Issue by lukaszbanasiak** [lukaszbanasiak/YAPA#15]
Ray Drew by email:

> Sometimes I start the break and continue working (realise I shouldn't do this!) then I don't remember if I'm in a pomodoro or a break - is there some way to indicate which I'm in - maybe the tooltip could say [start break] [stop break] when in a break or the task bar icon could have a different colour progressing when in a break?
##

**Comment by tkorcak** [comment]
This is exactly what I've wanted to post. When your app is on default settings (counting from 0 up) it is very hard to recognize if I'm on the rest period. It would be good to add the indicator which period is currently running.

**Comment by floatas** [comment]
Now when mouse is over timer, on right top corner minimize and close buttons are shown we could add 'Work' or 'Break' to the left side, and when period ended 'Start break' or 'Start work' or something similar. Also task bar has 'Paused' state with yellow color which we can use for break period.

**Comment by tkorcak** [comment]
I was playing a bit with it and the code and made a slight redesign - will do a fork and make a commit, so you can check and merge whatever you would like to. Will post here when it is done - need to do some refactoring and bugfixing first.

*Pomodoro in progress:*
![image](https://cloud.githubusercontent.com/assets/3337580/6139784/f03ce8c2-b18f-11e4-8377-7b33d84617d5.png)


*Mouse over:*
![image](https://cloud.githubusercontent.com/assets/3337580/6139763/a449bdbe-b18f-11e4-98a4-a830ee9d5d71.png)

*Period is over:*
![image](https://cloud.githubusercontent.com/assets/3337580/6139772/c043e42c-b18f-11e4-8946-e12cb3f1eb75.png)

*Period is over maximized:*
![image](https://cloud.githubusercontent.com/assets/3337580/6139778/da0eeb7c-b18f-11e4-874c-f19667477800.png)

**Comment by floatas** [comment]
I see a small problem with this template, it is really wide and it wont be possible to put timer in corner. Whe you finish it, I will try to make setting to switch templates between old one and this. Then it wouldn't be hard to make templates as plugins.

**Comment by tkorcak** [comment]
This template has been designed this way to have the possibility to lay over the window handle, which is the way I'm using it. I prefer to have the corner available for interactions. Anyway I'm not the only one and I see your point. It would be good to have the possibility to change the look according to a user's preference.

Unfortunatelly this template needed some deeper changes, but you'll see yourself. I'll push my version until saturday latest, possibly earlier. Will do my best to push it still today.

**Comment by floatas** [comment]
There's no hurry, I myself will have more time only on weekend to review your changes

**Comment by tkorcak** [comment]
Sorry for being late, but changes were more deeper than I thought. I was very likely rewritten half of the application (UI + logic).

Additionally I have been thinking about your requirement to have the possibility to pin this to a right corner and even I did not implemented this yet I've prepared the layout. Idea is to switch window buttons with clock when the user moves the window to right corner. Anyway still lot of work to do I think.

Now how it looks like now:

Minimized version:
![image](https://cloud.githubusercontent.com/assets/3337580/6205033/4a762348-b560-11e4-8e77-76f8581ad9d6.png)

Mouse over:
![image](https://cloud.githubusercontent.com/assets/3337580/6205034/648de158-b560-11e4-9f2b-e42bb385746a.png)

Pomodoro period started:
![image](https://cloud.githubusercontent.com/assets/3337580/6205044/c3b01638-b560-11e4-92a2-4690c5b9e474.png)

Pomodoro period started (including Quote source):
![image](https://cloud.githubusercontent.com/assets/3337580/6205047/ed1c5608-b560-11e4-845d-77290243bdb3.png)

Paused session:
![image](https://cloud.githubusercontent.com/assets/3337580/6205049/00aaf22e-b561-11e4-8809-9af1d7791dbc.png)


Check it on https://github.com/tkorcak/YAPA/tree/master/YAPA

**Comment by floatas** [comment]
Or just add option to switch timer location between left and right. New design looks really cool :+1: 
I tried to refactor application to separate view from application logic, still a lot of work left, not sure when will have time to continue. You can try to merge and continue my work, if you have time, main idea is to create helper classes and inject them, so other views can be made without duplicate code.
https://github.com/floatas/YAPA/tree/plugins

**Comment by tkorcak** [comment]
Guys, I'm pretty ill now, so I'm getting some rest. Hope I'll be fit next week so I can do some adjustments to this, but feel free to examine or contribute yourselves. See ya.

**Comment by floatas** [comment]
We went a bit too far from main issue, I created separate task to discuss about custom themes #21

**Comment by tkorcak** [comment]
Hi, just to add - in case you will do the merge and start the base on my changes then you can consider this ticket as solved/closed.

**Comment by fghber** [comment]
Wow, I love your new counter theme with all improved UI and the quotes @tkorc Chapeau!
I would really like to see this adapted in the main branch.

**Comment by floatas** [comment]
I don't believe we will change default YAPA theme, maybe with some small adjustments. I'm working on YAPA 2.0 (almost finished) and it will support custom themes, I will port this theme to it, hopefully @tkorc  won't mind.

**Comment by tkorc** [comment]
Hey @floatas, I won't mind at all :-) feel free...
Thank you @fghber anyway! Great it can make someone else's life more joyful :-) 👍

**Comment by floatas** [comment]
Fixed by adding icons, same as tkorc theme.
