### ISSUE TITLE
Crash upon entering settings by rightclick or after end of pomodoro

### ISSUE THREAD

**Issue by GoodKey** [lukaszbanasiak/YAPA#16]
When you install 1.2 run it and then right click to access settings the program crashes. It seems like it has to do with the time counter history, because that doesn't load.

~~As long as I don't go to settings the program seems to work fine.~~ (It crashes after 1 pomodoro)
I managed to change settings by manually editing the settings file.

After my first backwards counting pomodoro it crashed.

**Comment by NelsonReis** [comment]
I'm having the same issue, but couldn't find out what the problem was, even by replacing .exe, .sdf or .config files on my install folder with the ones from the source repo.

**Comment by lukaszbanasiak** [comment]
The same behavior on my computer at work. At home (laptop and vm) I didn't have this issue.
When i run exe from Visual Studio Release folder I don't have this problem.

**Comment by lukaszbanasiak** [comment]
I changed the portable version. Please test this file https://github.com/lukaszbanasiak/YAPA/releases/download/v1.2.0/Portable.zip. This are files from directory mentioned above (Visual Studio Release folder).

**Comment by GoodKey** [comment]
Works for me.

**Comment by lukaszbanasiak** [comment]
@GoodKey At what point? When you enter the settings, or when you finish pomodoro?

**Comment by GoodKey** [comment]
When I enter the settings. It has to do with the loading of the pomo
history.
(Perhaps also when finishing.)
(The settings seem to have reset.)

**Comment by floatas** [comment]
Seems like permission issue, try to delete database file that was installed. Database is created automatically on first write.

**Comment by GoodKey** [comment]
Deleted the database file from the portable version and that worked.

**Comment by floatas** [comment]
Can someone test install version too ? for me deleting that file fixed both versions.

**Comment by lukaszbanasiak** [comment]
If anyone can test the new installer? https://github.com/lukaszbanasiak/YAPA/releases/download/v1.2.0/Installer.exe

**Comment by GoodKey** [comment]
Will do.

**Comment by lukaszbanasiak** [comment]
@floatas 
What files do I need also included in setup.exe to work pomodoro history?
Default InstallShield are packing this files:
```
|   EntityFramework.dll
|   EntityFramework.SqlServer.dll
|   EntityFramework.SqlServerCompact.dll
|   WpfAnimatedGif.dll
|   Xceed.Wpf.Toolkit.dll
|   YAPA.exe
|   YAPA.exe.config
|
\---Resources
        ding.wav
        tick.wav
```

What about this files:
* System.Data.SqlServerCe.dll
* System.Data.SqlServerCe.Entity.dll

and dirs:
* amd64
* x86

**Comment by floatas** [comment]
Seems like all files are needed, just like in portable version. New installer works fine at work, but probably because all tools are installed. Looks like good time to set up virtual machine without dev tools for testing.

**Comment by floatas** [comment]
Bug that made application to crash was fixed, if someone still has problems with it please reopen or create new issue.
