### ISSUE TITLE
Github like pomodoro history isn't rectangle shaped and contrains wite tiles.

### ISSUE THREAD

**Issue by GoodKey** [lukaszbanasiak/YAPA#17]
![yapa](https://cloud.githubusercontent.com/assets/6448718/5941915/63f0e61e-a714-11e4-8d0a-d5d197ee61cf.png)

**Comment by floatas** [comment]
White space separates years, still thinking is this a bug or hidden feature ? Also it would be great to show months on top just like github.

**Comment by GoodKey** [comment]
Aah, I see :+1:

**Comment by floatas** [comment]
Removed white space and changed cells to be rectangular
