### ISSUE TITLE
What about 5 minutes-break?

### ISSUE THREAD

**Issue by Gennady-G** [lukaszbanasiak/YAPA#26]
Hi!

Thank You for great program, it is small and cool! :)

But I don't understand for what there is setting for long and short breaks in the settings? For now YAPA just counts work intervals, or I didn't find featuire to measure break? If not, do You plan?

For 5-minutes break intervals I forced to use other soft now(countdown in my phone) :)

**Comment by floatas** [comment]
Hello there, have you changed these settings ? It does work, you get 3 short breaks and then 1 long break.

**Comment by Rockietm** [comment]
Hi!

Hmm.. I understand, I was doing wrong.

When interval ends, YAPA rings and blinks red. I pressed "Stop", and when after break when I hit "Start" it started new. I need to always press "<b>Start</b>"..

**Comment by floatas** [comment]
When you press "Stop" you reset timer and start from beginning, press "Start" again and it will start pause ;)
