### ISSUE TITLE
Wrong placed counter, when brings to front from tray

### ISSUE THREAD

**Issue by Gennady-G** [lukaszbanasiak/YAPA#27]
I use widescreen monitor and I sticked windows task bar to the left side. And minimized Yapa appears here:

![yapa_2015-12-17_203553](https://cloud.githubusercontent.com/assets/5569346/11904856/a0036378-a5cb-11e5-8d0a-789d891b4ac3.png)

if I move:
![yapa_2015-12-17_212735](https://cloud.githubusercontent.com/assets/5569346/11904857/a01d5760-a5cb-11e5-8df3-a2bb0e3af5ec.png)

But I think it does not affect "normal users" :)
##

**Comment by Gennady-G** [comment]
imho it would be cool if YAPA save its position and restore from tray on its old place

**Comment by floatas** [comment]
Fixes made for positioning and offscreen.
