### ISSUE TITLE
Pomodoro count is reset without confirmation

### ISSUE THREAD

**Issue by Ytrog** [lukaszbanasiak/YAPA#28]
When I click stop or start multiple times it resets my pomodoro count for the day without asking if I want that and without a way to recover.

**Comment by floatas** [comment]
Can you give exact steps ?
Since all completed pomodoros are saved in database, maybe best would be to always load from db, if I remember correctly now every time you start application it starts from zero.

**Comment by floatas** [comment]
It seems there are two ways to fix this issue, not sure which one is better.

Start application and load next period so user could continue and when pressing reset
1) reset to loaded period.
2) reset to zero allowing user to start fresh cycle.

**Comment by tifon** [comment]
Fixed

**Comment by floatas** [comment]
Fixed
