### ISSUE TITLE
need an option which enable the clicking sound, it clicks during the working time

### ISSUE THREAD

**Issue by syler** [lukaszbanasiak/YAPA#30]
sometimes we need to hear something to notify us the time is flying, keep hard working on your job, don't waste your time, cannot give up, cannot die, not today, come on... hearing the click sound would remind me of "go, go, go".

even we can add more options for the sound, like white noise, the sound in coffee shop, street noise or what ever you can find.

it clicks all the time when working, currently we can hear the clicking when starting a task, and it disappears quickly.

And one last thing not related with the above: I don't know how to measure the time during 5 minutes reset.

**Comment by floatas** [comment]
Well there are two options:
1. We can add these sounds in dropdown and let user select what to play (different sounds for work\break). In this case we need to find sound files that could be used, without any licensing issues.
2. Add audio file selector one for work and one for break.

Well we can start from 2 and if later someone find any good sound that could be used we can embed them.

Can you expand a bit more on 5 min reset ?

**Comment by floatas** [comment]
Feel free to grab latest ClickOnce installer ant test it ;)

**Comment by syler** [comment]
that's awesome! great , thanks for these updates.

however, I don't find the clickonce installer, so I downloaded visual studio 2015 and re-build it myself, works great.

**Comment by floatas** [comment]
Link to installer is in #32  issue

**Comment by syler** [comment]
Hi man, consider to make this change in MainWindow.xaml.cs, sometimes if the working directory is not correct, the application startup will fail.

-            sysTrayIcon.Icon = new System.Drawing.Icon(@"Resources\pomoTray.ico", 40, 40);
+            sysTrayIcon.Icon = new System.Drawing.Icon(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"Resources\pomoTray.ico"), 40, 40);


another thing is I found in this setup project, some output files are using absolute path, so it does not compile on my machine, maybe we can use this way:
http://stackoverflow.com/questions/15390098/installshield-le-relative-paths-to-file

**Comment by floatas** [comment]
Fixed path for sysTrayIcon.Icon and created separate issue #35 for setup project

**Comment by floatas** [comment]
Maybe you can make pull request with all changes ?
Pull request would allow to discuss and review changes much easier.
