### ISSUE TITLE
Make new releases available on GitHub

### ISSUE THREAD

**Issue by NelsonReis** [lukaszbanasiak/YAPA#31]
YAPA has a lot of new contributions since its last available release (1.2.0 on 27 Jan 2015), but they are not available for download.

It would be very helpful to make it ready to download and install, without having to clone the repo and build.

**Comment by floatas** [comment]
New installers are made by @lukaszbanasiak (lets tag for notifications).

Also I done some work on my private build\test server to host click once installers. Still need to add version info to YAPA (from which commit it was built). Hopefully this week I will find time to finish and then we will have nightly YAPA builds with auto updates.

**Comment by lukaszbanasiak** [comment]
@floatas that's great news, can wait for this.
I'm planned for weekend also work at YAPA.

**Comment by NelsonReis** [comment]
That's great news, guys! Thanks.

**Comment by floatas** [comment]
In YAPA options version is 1.2.0, bet when you right click on YAPA.exe and go to details it shows 1.0.0.1 which is taken from IconSet.res Version section. We should refactor so it would show same version everywhere. 
How to change version on build\publish is still mystery for me.

**Comment by floatas** [comment]
Click once installer available [here](https://github.com/lukaszbanasiak/YAPA/issues/32). If there are any issues, please leave comment in that thread.

**Comment by NelsonReis** [comment]
Do you know where is the database located?
The ClickOnce app got installed on `C:\Users\[username]\AppData\Local\Apps\2.0\...`, but I couldn't find where the `YAPA.DatabaseContext.sdf` is.

**Comment by floatas** [comment]
It should be in local app data, for me it's:
%localappdata%\Apps\2.0\Data\ZHMML037.0LT\A5O7EZ8R.L2R\yapa..tion_0000000000000000_0001.0000_daf1a10a28088f14\Data 

Might be good idea to add setting for db location.

**Comment by NelsonReis** [comment]
Nice, found it. Thanks.

**Comment by lukaszbanasiak** [comment]
I have added link to ClickOnce installer on website
