### ISSUE TITLE
YAPA ClickOnce installer

### ISSUE THREAD

**Issue by floatas** [lukaszbanasiak/YAPA#32]
Made ClickOnce installer with auto updates. First time configuring ClickOnce, so if there are any issues, just leave comment.

[Download](http://s1.floatas.net/installers/yapa/YAPA.application)

**Comment by lukaszbanasiak** [comment]
I've changed link on website https://github.com/lukaszbanasiak/YAPA/commit/51ac2b46c067534da7d4b6d5f12e3fe2f7b7de01
