### ISSUE TITLE
Please contac me

### ISSUE THREAD

**Issue by lukaszbanasiak** [lukaszbanasiak/YAPA#33]
@floatas pleas contact with me via http://banasiak.me/contact/
I couldn't find anywhere your mail :)

**Comment by floatas** [comment]
I can't "Wystąpiły błedy. Spróbuj później albo skontaktuj się w inny sposób."
You can contact me using this email: 4d49daef@opayq.com
It's proxy (doesn't expire) and forwards to my real email, I will answer from real one and will remove this proxy email :)

**Comment by lukaszbanasiak** [comment]
@floatas sent
