### ISSUE TITLE
The clickonce installer is terrifying

### ISSUE THREAD

**Issue by voronoipotato** [lukaszbanasiak/YAPA#42]
Win10 you get some warnings, unknown publisher. At no point do you think you're doing a good thing by installing it. What are some strategies to make this less scary?

**Comment by floatas** [comment]
Only way to make it less scary, is to buy code signing cert which costs ~170 eur per year. Other option would be to make portable version, but then there would be no auto updates.

I might buy this cert for my personal use and sign this project as well in near future.

**Comment by Gennady-G** [comment]
ClickOnce allows to launch application only with active internet connection? And what about about offline-clients?

**Comment by voronoipotato** [comment]
offline clients probably couldn't have downloaded the clickonce installer anyway...

**Comment by Gennady-G** [comment]
:)

**Comment by reksc** [comment]
+1, terrifying indeed :)

**Comment by fghber** [comment]
I will ask around.
Another possible solution would be to turn YAPA/2 into an official Windows Store app.
That would take away the need of individual signing cert.

**Comment by floatas** [comment]
One way to make it look safe.
Right click on Setup.exe and click unblock.
![image](https://user-images.githubusercontent.com/7883111/28666567-ca3e47bc-72bf-11e7-99c1-889ee282ba09.png)

Then that scary window will not be shown.
