### ISSUE TITLE
Start minimized?

### ISSUE THREAD

**Issue by Gennady-G** [lukaszbanasiak/YAPA#48]
Hi!

Thank You for great soft, use it every day. Earlier You added "ShowInTaskbar" option for me, thank You much!

```
            <setting name="ShowInTaskbar" serializeAs="String">
                <value>False</value>
            </setting>
```

Do we have ability to start YAPA minimized?

Best regards,  Gennady

**Comment by floatas** [comment]
Hi, currently there is no such option. Do you mean minimized or in system tray ?

**Comment by Gennady-G** [comment]
Hi! 
In my case minimized to system tray.. :) I start Yapa from shortcut form shell:startup folder, and it would be great if it starts minimized to tray

Best regards, Gennady

**Comment by floatas** [comment]
Added option to start minimized
            <setting name="StartInSystemTray" serializeAs="String">
                <value>True</value>
            </setting>

**Comment by Gennady-G** [comment]
Hi **floatas**!

Great! Thank You much! :)

Best regards,  
Gennady
