### ISSUE TITLE
Option to hide windows 10 taksbar 

### ISSUE THREAD

**Issue by rickstaa** [lukaszbanasiak/YAPA#50]
Is it possible to hide the taskbar icon when workrave is minimized? 

Maybe something like:

    private void frmMain_Resize(object sender, EventArgs e)
    {
        if (FormWindowState.Minimized == this.WindowState)
        {
           mynotifyicon.Visible = true;
           mynotifyicon.ShowBalloonTip(500);
           this.Hide();
        }
    
        else if (FormWindowState.Normal == this.WindowState)
        {
           mynotifyicon.Visible = false;
        }
    }

[https://stackoverflow.com/questions/7625421/minimize-app-to-system-tray](url)

**Comment by floatas** [comment]
Yes, there is setting "Minimize to tray". If checked, on minimize app will be hidden from taskbar. 

We don't have baloonTips, I think it would be nice addition. As of now only sound notification is played on work\break end.

**Comment by rickstaa** [comment]
Ah I saw that option but appearently it is not working on my computer.

Computer Info:
OS Name:                       Microsoft Windows 10 Home
OS Version:                    10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:                Multiprocessor Free
Registered Organization:   Hewlett-Packard Company
Original Install Date:     21/10/2016, 09:35:10
System Boot Time:          03/06/2017, 11:16:43
System Manufacturer:       HP
System Model:              HP ZBook Studio G3
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz
BIOS Version:              HP N82 Ver. 01.16, 14/04/2017
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16,265 MB
Available Physical Memory: 8,653 MB
Virtual Memory: Max Size:  18,697 MB
Virtual Memory: Available: 8,671 MB
Virtual Memory: In Use:    10,026 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\RICKS-WINDOWS
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB3150513
                           [02]: KB3176935
                           [03]: KB3176937
                           [04]: KB3199209
                           [05]: KB3199986
                           [06]: KB3211320
                           [07]: KB4013418
                           [08]: KB4020821
                           [09]: KB4019472
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.21
                                 [02]: fe80::2d57:c46f:2f6b:ee86
                           [02]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth-netwerkverbinding
                                 Status:          Media disconnected
                           [04]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [05]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by floatas** [comment]
When you check that option and minimize application, what happens ? Do you see system tray icon ?

**Comment by rickstaa** [comment]
Dear floatas, Thanks for your message. No I just keep having the task bar icon. Even if I reload the program. No system tray icon.

**Comment by floatas** [comment]
Is there any other machine where you could test this ? I tested YAPA on Win8, Win10 pro without any issues. Not even sure how to help there, if it doesn't even throw exceptions. Maybe some win 10 settings prevent system tray...

Also you can try [YAPA 2.0](https://github.com/YetAnotherPomodoroApp/YAPA-2/releases), it has all current functionality and more, also it uses different installer.

**Comment by rickstaa** [comment]
Ah the hide in YAPA 2.0 works fine however it doesn't show an icon so I can access the program. Is there a way to reset the settings?

**Comment by floatas** [comment]
There are two files that you can remove: localSettings.json and settings.json
C:\Users\<username>\Documents\YAPA2

Can you zip these files\or just copy its content there or in YAPA 2 repository issues ? I would like to investigate, maybe there is a bug.

**Comment by rickstaa** [comment]
Thanks for the support floatas. Here are the files.

https://we.tl/39sNkVJjXy

After deleting these files and reinstalling the program is working fine again. However, the app still won't minimize to tray when enabled. But since YAPA 2 has a nice icon I don't mind.

HOW I THINK I CREATED THE PROBLEM:
- Go to settings --> plugins.
- Enable minimize to tray.
- Restart application.
- Go to settings.
    - Plugins now has a fold out menu option. 

I think here I set one of the minimize buttons to enable and the other to disable or I set both to enable. 

Hope this helps. If you need any more help don't hesitate to ask.

Greetings,

**Comment by floatas** [comment]
When you select Plugins, plugin list is shown. When you enable plugin and restart app, plugin configuration is shown under Plugins tab. Plugin and plugin setting has same name...

YAPA 2 is same app as YAPA 1 just refactored, so most naming is same.
Now that I think, it looks a bit confusing, should have chosen better names.

Does it work with this configuration ?
![image](https://user-images.githubusercontent.com/7883111/27222411-0a7d4e56-5284-11e7-8e5d-83b38a566906.png)

![image](https://user-images.githubusercontent.com/7883111/27222414-119c72d4-5284-11e7-8b73-eed7c8584d5f.png)


What do you mean by can't put back ? After app restart same theme is shown ?

**Comment by rickstaa** [comment]
Yea after setting the "movivational theme". The timer disappears and I can't set it back to "Yapa 1" theme without removing preferences. For the Minimize to tray option that setups works. Now only the timer is shown.

I know now what went work. I think the "motivational" theme is not working on my pc and when I set both the "movitvation" theme and "minimize tray" to enable I'm unable to acces the settings.

Thanks,
Greetings,
Rick,

**Comment by floatas** [comment]
Motivational theme opens settings with button next to minimize and close (when you right click it does nothing)

**Comment by rickstaa** [comment]
Ah, thanks. Unfortunately, no timer is shown when I set it to "Motivational theme". However, I'm happy with the setup I have now 👍.

**Comment by Gennady-G** [comment]
> But, would it be possible to hide the icon on the taskbar? There's already an option to 'minimize to tray', but it would be nice if it would minimize to tray even when the timer itself is active.

Hmm..
There already is "ShowInTaskbar" flag in YAPA.exe.config, tested now but it gives exception for me(YAPA 1.0)..

**Comment by Andre85** [comment]
Oh, that's awesome. tested it and it works fine for me(at least for the moment, doesn't crash on starting the pomodoro or anything). 

I think it should be an option visible in the menu though. Also it would be really nice if the music would resume after starting a new pomodoro.

Really great app.

**Comment by floatas** [comment]
Hello @Andre85 , thank you for your feedback!
We are working on YAPA 2 (you can download from [here](https://github.com/YetAnotherPomodoroApp/YAPA-2)). 

> But, would it be possible to hide the icon on the taskbar? There's already an option to 'minimize to tray', but it would be nice if it would minimize to tray even when the timer itself is active.

This is configurable in YAPA 2.

> The only other thing that I'd suggest is maybe replacing the installer and giving the user an option to install it somewhere, at the moment it seems to require internet connection to function? Not sure.

For YAPA 2 we are using different installer ([Squirrel](https://github.com/Squirrel/Squirrel.Windows)), this installer doesn't have option to install to different location, but it's open source. I could try to look into that. Since we changed installer, app no longer requires internet connection to function.

> Also it would be really nice if the music would resume after starting a new pomodoro.
This is something that we could implement, but most likely in YAPA 2. If we add Pause/Resume we might as well add folder support, select folder with music and it would continue to play next song.
